version: '3.7'
x-challenge:
  &challenge
  image: python:3.12-slim
  profiles:
    - unittest
  environment:
    PYTHONUNBUFFERED: '1'
    PIP_ROOT_USER_ACTION: ignore
  volumes:
    - ./coverage:/app/coverage
    - ./requirements.txt:/app/requirements.txt
    - ./src:/app/src
    - ./tests:/app/tests
    - python-packages:/usr/local/lib/python3.12/site-packages
  working_dir: /app
services: 
  unittest:
    <<: *challenge
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r requirements.txt
        python -m unittest
  coverage:
    <<: *challenge
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r requirements.txt
        python -m coverage run -m unittest -b 2> /dev/null
        python -m coverage html -d /app/coverage
        python -m coverage report -m --fail-under=96
  lint:
    <<: *challenge
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r /app/requirements.txt
        python -m pylint src
volumes: 
  python-packages:
