version: '3.7'
services: 
  unittest:
    image: python:3.12-slim
    profiles:
      - unittest
    environment:
      PYTHONUNBUFFERED: '1'
      PIP_ROOT_USER_ACTION: ignore
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
      - ./tests:/app/tests
      - python-packages:/usr/local/lib/python3.12/site-packages
    working_dir: /app
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r requirements.txt
        python -m unittest
  coverage:
    image: python:3.12-slim
    profiles:
      - unittest
    environment:
      PYTHONUNBUFFERED: '1'
      PIP_ROOT_USER_ACTION: ignore
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
      - ./tests:/app/tests
      - ./coverage:/app/coverage
      - python-packages:/usr/local/lib/python3.12/site-packages
    working_dir: /app
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r requirements.txt
        python -m coverage run -m unittest -b 2> /dev/null
        python -m coverage html -d /app/coverage
        python -m coverage report -m --fail-under=96
  lint:
    image: python:3.12-alpine
    profiles:
      - unittest
    environment:
      PYTHONUNBUFFERED: '1'
      PIP_ROOT_USER_ACTION: ignore
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
      - ./tests:/app/tests
      - python-packages:/usr/local/lib/python3.12/site-packages
    working_dir: /app
    command: 
      - /bin/sh
      - -c
      - |
        pip install -q -r /app/requirements.txt
        python -m pylint src
volumes: 
  python-packages:
